### ISSUE TITLE
Generated XML does not include posts

### ISSUE THREAD

**Issue by dimitri-bourreau** [tadashi-yama1012/next-rss#2]
Hi @tadashi-yama1012 , thank you for your work!

## Problem

Unfortunately, I can not make it work. 

Here is my `next-rss.js`:

```js
module.exports = {
  siteTitle: "Dimitri Bourreau : Développeur",
  siteDescription: "Dimitri Bourreau : Développeur",
  siteLanguage: "fr",
  siteCopyright: "Dimitri Bourreau",
  siteUrl: "https://dimitribourreau.me",
  outDir: "public",
  postsDir: "posts",
};
```

My blog posts are in `/posts`, for example a blog post would be `/posts/my-post.md`.

---

## Generated files

When I use `npx next-rss`, here are the generated XML files:

_/public/atom.xml_

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>https://dimitribourreau.me</id>
    <title>Dimitri Bourreau : Développeur</title>
    <updated>2020-12-20T12:11:40.978Z</updated>
    <generator>https://github.com/jpmonette/feed</generator>
    <link rel="alternate" href="https://dimitribourreau.me"/>
    <subtitle>Dimitri Bourreau : Développeur</subtitle>
    <rights>Dimitri Bourreau</rights>
</feed>%    
```

_/public/rss.xml_
```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
    <channel>
        <title>Dimitri Bourreau : Développeur</title>
        <link>https://dimitribourreau.me</link>
        <description>Dimitri Bourreau : Développeur</description>
        <lastBuildDate>Sun, 20 Dec 2020 12:11:40 GMT</lastBuildDate>
        <docs>https://validator.w3.org/feed/docs/rss2.html</docs>
        <generator>https://github.com/jpmonette/feed</generator>
        <language>fr</language>
        <copyright>Dimitri Bourreau</copyright>
    </channel>
</rss>% 
```

---

I must miss something obvious, thanks for your help! 🙏
ありがとう！

**Comment by tadashi-yama1012** [comment]
Thanks for your message!

next-rss requires files to be pre-built by Next.js in order to work.
Please try running "npx next build" and then "npx next-rss".

Sorry for the inconvenience!

**Comment by dimitri-bourreau** [comment]
Yes, I already did that, you try it out yourself if you want to check it out: https://github.com/dimitri-bourreau/next-blog/tree/rss. ✅

**Comment by tadashi-yama1012** [comment]
The library has been upgraded.

As you pointed out, there was a flaw in the library. I am truly sorry for that.

In the upcoming version 1.0.1, we have changed it to refer to the directory with the value set in the "postsDir" property (until now, it only referred to the "posts" directory).

This allows you to output the "blog" directory under the "page" directory of your blog site as RSS.

Please configure it as follows

```js
module.exports = {
  siteTitle: "Dimitri Bourreau : Développeur",
  siteDescription: "Dimitri Bourreau : Développeur",
  siteLanguage: "fr",
  siteCopyright: "Dimitri Bourreau",
  siteUrl: "https://dimitribourreau.me",
  outDir: "public",
  postsDir: "blog",
};
```

**Comment by dimitri-bourreau** [comment]
Hi @tadashi-yama1012 ,

Your update does the job and works perfectly! ✅

I am glad I could help you improve this very useful package. 🙂

---

I have a last request, the Readme file advices to install express-rss. But using npx does not require to install the package locally. 🙂

---

I wish you the best for 2021, thanks for this package I love it!
